name: Compilation & tests
on:
  push:
    branches-ignore:
      - 'ga-ignore-**'
  pull_request:
    branches-ignore:
      - 'ga-ignore-**'
env:
  MIRROR_URL: "git@github.com:EpitechPromo2028/B-OOP-400-NAN-4-1-raytracer-jean.bizeul.git"
  BINARY: "raytracer"
jobs:
  check_mirror_repo:
    name: "Check mirror repository"
    runs-on: ubuntu-latest
    outputs:
        check_repo: ${{ steps.check_repo.outputs.repo }}
    steps:
      - id: check_repo
        run: |
          cleaned_url=$(echo "$MIRROR_URL" | sed 's/git@github.com://' | sed 's/.git$//')
          if [[ "${{ github.repository }}" == $cleaned_url ]]; then
            echo "repo=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          echo "repo=false" >> "$GITHUB_OUTPUT"
  check_program_compilation:
    name: compilation
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: make
        timeout-minutes: 2
        run: make
      - name: looking for executables
        if: hashFiles(env.BINARY) == ''
        run: |
          echo "::error title="missing executable(s)!"::"
          exit 1
      - name: clean
        run: make clean
  run_tests:
    name: tests
    needs: check_program_compilation
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: running tests
        timeout-minutes: 2
        run: make tests_run
  push_to_mirror:
    name: pushing
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          ${{ env.MIRROR_URL }}
        ssh_private_key:
          ${{ secrets.GIT_SSH_PRIVATE_KEY }}
